### PR TITLE
Dev slentzen

### PR DESCRIPTION
**Pull request by slentzen**
Can you confirm that you are able to generate the .idea/ folder with
$sbt gen-idea
and then you can import it into IntelliJ IDEA?
I am able to do so and can also compile with SBT

There are some Scala specific warnings regarding the source code itself, but it's not related to SBT.

I am using the latest snapshot of SBT gen-idea as added to project/plugins.sbt

I have also added a bunch of generated ignores to .gitignore so it now completely ignores the .idea/ folder. This folder truly is a problematic folder. Once you buy a new computer, or have reformatted your old one. I guarantee you that you won't be able to rebuild your projects as it seems that a lot of the project specific dependencies, modules etc. in IntelliJ leaks over into the "global configuration". So it's easy to forget one added a library a long time ago and is relying on it.

I will start doing the things we suggested in SBT as soon as you can confirm that it works with the /idea folder ignored and using SBT gen-idea.

I was thinking the best way to do all of these specific milestones is if you open them up as issues here on GitHub. You can even annotate them as milestones and "color code them".

Todoist may work great for more abstract tasks, but for programming I find we often end up with all too generic descriptions and tasks that just aren't clear enough on what exactly to do.

So opening an issue I can comment on and "close" for each specific task you want done here on my fork of nounou, hayabaya, breeze etc. Would be the best way to do it IMHO.

I will stay home Tuesday and be back Wednesday. We can try pair-programming/ online meeting using VNC on Thursday if that's alright with you, and then meeting IRL again Friday.

@ktakagaki

### CODE REVIEW

**Comment by ktakagaki** [comment]
image

**Comment by ktakagaki** [comment]
Importing the sbt file within the Idea GUI does work for the most part. I hope the ?github plugin works for Idea too..

**Comment by ktakagaki** [comment]
> I have also added a bunch of generated ignores to .gitignore so it now completely ignores the .idea/ folder. This folder truly is a problematic folder. Once you buy a new computer, or have reformatted your old one. I guarantee you that you won't be able to rebuild your projects as it seems that a lot of the project specific dependencies, modules etc. in IntelliJ leaks over into the "global configuration". So it's easy to forget one added a library a long time ago and is relying on it.

Don't have to guarantee it for me. I've gone through this exact problem 2+ times already. 

The issue is not simple inertia: the dependency part should be relatively painless. But what will probably be painful (if at all possible) is specifying the builds (with flat unpacked *.jar files, which can be read from Mathematica/Matlab), I've tried before. Their classpaths don't deal well with ```*.jar``` s inside ```*.jar``` s.

That's for next week.

**Comment by slentzen** [comment]
How did you do it?

I enter the project on the commandline and type
$sbt gen-idea

This will create the .idea/ folder for me. Then I open up IntelliJ and import the project by opening the "build.sbt". I know on my computer I have to open/import the nounou/build.sbt file and not the folder, otherwise IntelliJ won't import the project.

Halway through IntelliJ will complain about certain modules not being loaded and it asks me to reload them, It then opens a file open window. There I navigate to the nounou root project folder and say open. Afterwards I will pop up with the two parts of nounou as core modules to import.

Next window IntelliJ asks if it should open existing project, or delete it and re-import everything. I click "Open existing project", and then as the last option I choose to open in this window (not important).

Do you get any errors when running  **"$sbt gen-idea"**?

```{bash}
$cd nounou
$sbt gen-idea
[info] Loading project definition from /home/cain/KentaWork/nounou/project
[info] Set current project to nounou (in build file:/home/cain/KentaWork/nounou/)
[info] Creating IDEA module for project 'nounou' ...
[warn] Multiple dependencies with the same organization/name but different versions. To avoid conflict, pick one version:
[warn]  * org.scala-lang:scala-reflect:(2.11.0, 2.11.7)
[warn]  * org.scala-lang.modules:scala-parser-combinators_2.11:(1.0.1, 1.0.4)
[warn]  * org.scala-lang.modules:scala-xml_2.11:(1.0.1, 1.0.4)
[info] Resolving jline#jline;2.12.1 ...
[info] Excluding folder target
[info] Created /home/cain/KentaWork/nounou/.idea/IdeaProject.iml
[info] Deleted existing library files
[info] Created /home/cain/KentaWork/nounou/.idea
[info] Excluding folder /home/cain/KentaWork/nounou/target
[info] Created /home/cain/KentaWork/nounou/.idea_modules/nounou.iml
[info] Created /home/cain/KentaWork/nounou/.idea_modules/nounou-build.iml
```

**Comment by slentzen** [comment]
nounou_load_01

I can confirm that I was able to completely delete the .idea/ folder, run **$sbt gen-idea** again and import the project into IntelliJ without any issues.
There was a warning about colliding dependencies, but it's not fatal nor related to importing

See the two attached pictures

nounou_load_02

**Comment by ktakagaki** [comment]
Hmm, will try again in the evening, that's exactly what I did too, off the cmd prompt

**Comment by slentzen** [comment]
I'll try on the laptop tomorrow. It could be that it's a windows specific issue. Or it could be due to lacking handling of locales when there's Japanese mixed in. I've often had those sort of issues on windws when the base installation is German, and I've changed the UI to be English. It one time went as far as completely preventing me from uninstalling a program as it was stored under C:\Users\Sören\AppData\roaming\programX. Having the umlaut "ö" in the pathname was the issue. The packaging program/uninstaller couldn't handle this exotic character and failed. So it was not possible to uninstall. It could be a similar issue here.

If we are not able to solve the issue I suggest we dump the log, and open up an issue request on https://github.com/mpeltonen/sbt-idea as I am using the latest SNAPSHOT and it would be a genuine bug then.

**Comment by ktakagaki** [comment]
That's unlikely, I avoid non-standard characters in main paths pretty
religiously. Comes from the time of 8 bit characters in dos/windows, where
Japanese versions had these strange 16 bit overlays to display
Japanese/Chinese, and this could really cause issues on paths, etc...


*Kentaroh Takagaki, MD PhD (高垣 堅太郎)*
     Group Leader, AG Neuro-Optics
     Department Systems Physiology of Learning
     Leibniz Institute for Neurobiology
     <kentaroh.takagaki@lin-magdeburg.de
<kentaroh.takagaki@ifn-magdeburg.de>>
     http://www.lin-magdeburg.de/en/ifn_mp.jsp?member=ktakagak&fc=T

**Pull request merged**
